/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/my-blogs/': RouteRecordInfo<'/my-blogs/', '/my-blogs', Record<never, never>, Record<never, never>>,
    '/my-projects/': RouteRecordInfo<'/my-projects/', '/my-projects', Record<never, never>, Record<never, never>>,
    '/my-skills/': RouteRecordInfo<'/my-skills/', '/my-skills', Record<never, never>, Record<never, never>>,
  }
}
