# 将静态内容部署到 GitHub Pages 的简易工作流程
name: Deploy static content to Pages

on:
  # 仅在推送到默认分支时运行。
  push:
    branches: ["master"]

  # 这个选项可以使你手动在 Action tab 页面触发工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages。
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发的部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 单次部署的工作描述
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Config pnpm registry
        run: |
          pnpm config set registry https://registry.npmmirror.com
          pnpm config set @vuetify:registry https://registry.npmmirror.com
          pnpm config set disturl https://npmmirror.com/mirrors/node
          pnpm config set electron_mirror https://npmmirror.com/mirrors/electron/
          pnpm config set sass_binary_site https://npmmirror.com/mirrors/node-sass
          pnpm config set sharp_binary_host https://npmmirror.com/mirrors/sharp
          pnpm config set sharp_libvips_binary_host https://npmmirror.com/mirrors/sharp-libvips
          pnpm config set sqlite3_binary_site https://npmmirror.com/mirrors/sqlite3

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --reporter=silent
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Build
        run: pnpm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: "./docs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
